/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesGraficas;
import libreriainternacional.*;
import libreriainternacional.Login;
/**
 *
 * @author Katherine
 */
public class InterfazSede extends javax.swing.JFrame {

    /**
     * Creates new form InterfazSede
     */
    public InterfazSede() {
        initComponents();
        this.setLocationRelativeTo(null); //centrarlo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHeredia = new javax.swing.JButton();
        btnCartago = new javax.swing.JButton();
        btnSanJose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHeredia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Heredia.png"))); // NOI18N
        btnHeredia.setBorderPainted(false);
        btnHeredia.setContentAreaFilled(false);
        btnHeredia.setFocusPainted(false);
        btnHeredia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHerediaMouseClicked(evt);
            }
        });
        getContentPane().add(btnHeredia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        btnCartago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cartago.png"))); // NOI18N
        btnCartago.setBorderPainted(false);
        btnCartago.setContentAreaFilled(false);
        btnCartago.setFocusPainted(false);
        btnCartago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCartagoMouseClicked(evt);
            }
        });
        getContentPane().add(btnCartago, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, -1));

        btnSanJose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/San Jose.png"))); // NOI18N
        btnSanJose.setBorderPainted(false);
        btnSanJose.setContentAreaFilled(false);
        btnSanJose.setFocusPainted(false);
        btnSanJose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSanJoseMouseClicked(evt);
            }
        });
        getContentPane().add(btnSanJose, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sede.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSanJoseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSanJoseMouseClicked
        // TODO add your handling code here:
        Sede sede = new Sede();
        sede.seleccionSede(1);
        this.dispose();
    }//GEN-LAST:event_btnSanJoseMouseClicked

    private void btnHerediaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHerediaMouseClicked
        // TODO add your handling code here:
        Sede sede = new Sede();
        sede.seleccionSede(2);
        this.dispose();
    }//GEN-LAST:event_btnHerediaMouseClicked

    private void btnCartagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCartagoMouseClicked
        // TODO add your handling code here:
        Sede sede = new Sede();
        sede.seleccionSede(3);
        this.dispose();
    }//GEN-LAST:event_btnCartagoMouseClicked

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazSede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazSede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazSede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazSede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazSede().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCartago;
    private javax.swing.JButton btnHeredia;
    private javax.swing.JButton btnSanJose;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
